name: Build Maven Library

on:
  push:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@ab072da241b5022aa3b0f7010c860959945ce1b5 # v0.3.3
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '21'
      publish-goals: 'deploy -Dmaven.test.skip=true -Dmdep.analyze.skip'
